#!/bin/bash

docker build \
 --build-arg DEVPI_SERVER_ACCESS=$DEVPI_SERVER_ACCESS \
 --build-arg DEVPI_SERVER_IP=$DEVPI_SERVER_IP \
 --build-arg DEVPI_SERVER_PORT=$DEVPI_SERVER_PORT \
 -t $IMAGE_NAME .
